version: '3.8'
services:
  task:
    image: postgres:16.2
    container_name: adminio_pg
    restart: always
    environment:
      POSTGRES_DB: adminiodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1489
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432